export const HEADERTABLEROOM = [
  {
    text: " ",
    style: {
      maxWidth: "40px",
      width: "40px",
    },
    classState: "move",
    field: "sort",
  },
  {
    text: " ",
    style: { width: "50px" },
    classState: "",
    field: "id",
  },
  {
    text: "Tên phòng",
    style: { width: "101px" },
    classState: "",
    field: "name",
  },
  {
    text: "Diện tích",
    style: { width: "101px" },
    classState: "",
    field: "area",
  },
  {
    text: "Giá thuê",
    style: { width: "101px" },
    classState: "",
    field: "room_amount",
  },
  {
    text: "Mức giá tiền cọc",
    style: { width: "101px" },
    classState: "",
    field: "deposit_contract_amount",
  },
  {
    text: "Khách thuê",
    style: { width: "101px" },
    classState: "",
    field: "customers",
  },
  {
    text: "Số lượng người ở tối đa",
    style: { width: "109px" },
    classState: "",
    field: "maximun_menber",
  },
  {
    text: "Ngày lập hoá đơn",
    style: { width: "70px" },
    classState: "",
    field: "circle_day",
  },
  {
    text: "Chu kỳ thu tiền",
    style: { width: "70px" },
    classState: "",
    field: "circle_month",
  },
  {
    text: "Ngày vào ở",
    style: { width: "101px" },
    classState: "",
    field: "date_join",
  },
  {
    text: "Thời hạn hợp đồng",
    style: { width: "101px" },
    classState: "",
    field: "date_terminate",
  },
  {
    text: "Tình trạng",
    style: { width: "101px" },
    classState: "",
    field: "status",
  },
  {
    text: "Tài chính",
    style: { width: "101px" },
    classState: "",
    field: "active_status",
  },
  {
    text: " ",
    style: { width: "50px" },
    classState: "pointer",
    field: "action",
  },
];
