export let ROOMOBJECT = [
  {
    id: "1",
    status: ["is_active"],
    active_status: ["chờ kỳ thới thu"],
    area: "15",
    room_amount: "3000000",
    deposit_contract_amount: "3000000",
    customers: "1",
    circle_day: "20",
    circle_month: "1",
    date_join: "10/9/2023",
    date_terminate: "10/9/2033",
    maximun_member: "3",
  },
  {
    id: "2",
    status: ["is_empty"],
    active_status: ["chưa thể thu tiền"],
    area: "15",
    room_amount: "3000000",
    deposit_contract_amount: "0",
    customers: "0",
    circle_day: "20",
    circle_month: "1",
    date_join: "",
    date_terminate: "",
    maximun_member: "3",
  },
  {
    id: "3",
    status: ["is_active", "is_expire"],
    active_status: ["cần thu"],
    area: "15",
    room_amount: "3000000",
    deposit_contract_amount: "3000000",
    customers: "2",
    circle_day: "20",
    circle_month: "1",
    date_join: "20/12/2023",
    date_terminate: "20/12/2033",
    maximun_member: "3",
  },
];
